<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <TargetFrameworks>net48</TargetFrameworks>
        <ApplicationIcon>$(ProjectDir)..\..\legod.ico</ApplicationIcon>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <GenerateProgramFile>false</GenerateProgramFile>
        <!-- Microsoft.NET.Test.Sdk 会带Main函数导致重复定义-->
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.Web.WebView2"/>
        <PackageReference Include="TouchSocket" />

        <PackageReference Include="WPF-UI.Tray"/>
        <PackageReference Include="WPF-UI"/>
        <Reference Include="System.Net.Http"/>
        <Reference Include="Microsoft.Extensions.Configuration"/>
        <Reference Include="Microsoft.Extensions.Configuration.Ini"/>
        <ProjectReference Include="../LegodPause.Core/LegodPause.Core.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="JetBrains.Profiler.Api"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit.Analyzers"/>
        <PackageReference Include="NUnit3TestAdapter"/>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
        <Reference Include="System.Text.Encoding.CodePages"/>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETCoreApp'">
        <Reference Include="System.Text.Json"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>


    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>


    <ItemGroup>
        <Page Update="Properties\Style.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>


    <ItemGroup>
        <Content Include="$(SolutionDir)..\config.ini" Condition="Exists('$(SolutionDir)..\config.ini')">
            <Link>config.ini</Link>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>


    <Target Name="PostPublish" AfterTargets="Publish">
        <Delete Files="$(PublishDir)$(AssemblyName).exe.config"/>
    </Target>

</Project>
