<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>

        <ApplicationIcon>$(SolutionDir)..\legod.ico</ApplicationIcon>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <GenerateProgramFile>false</GenerateProgramFile>  <!-- Microsoft.NET.Test.Sdk 会带Main函数导致重复定义-->
    </PropertyGroup>


  

    <ItemGroup>
        <PackageReference Include="Microsoft.Web.WebView2" Version="*"/>

        <PackageReference Include="WPF-UI.Tray" Version="*"/>
        <PackageReference Include="WPF-UI" Version="*"/>
      
        <ProjectReference Include="..\LegodPause.Service\LegodPause.Service.csproj"/>
    </ItemGroup>


    <!--    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETCoreApp'">-->
    <!--        <PackageReference Include="System.Text.Json" Version="4.7.2"/>-->
    <!--    </ItemGroup>-->


    <Target Name="PostPublish" AfterTargets="Publish">
        <Delete Files="$(PublishDir)$(AssemblyName).exe.config"/>
    </Target>
</Project>
