<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <GenerateProgramFile>false</GenerateProgramFile>
    <!-- Microsoft.NET.Test.Sdk 会带Main函数导致重复定义-->
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="JetBrains.Profiler.Api" Version="1.4.10" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="NUnit" Version="4.2.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.4.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
    <PackageVersion Include="WPF-UI.Tray" Version="4.0.3" />
    <PackageVersion Include="WPF-UI" Version="4.0.3" />
    <PackageVersion Include="System.Text.Json" Version="9.0.11" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
    <Reference Include="System.Text.Encoding.CodePages" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETCoreApp'">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="JetBrains.Profiler.Api" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <Using Include="NUnit.Framework" />
  </ItemGroup>
</Project>